from app.config import settings

CONVERSATION_CONTEXT_MAX_MESSAGES = settings.CONVERSATION_CONTEXT_MAX_MESSAGES
CONVERSATION_CONTEXT_TOKEN_BUDGET = settings.CONVERSATION_CONTEXT_TOKEN_BUDGET
CONVERSATION_SUMMARY_TRIGGER_MESSAGES = settings.CONVERSATION_SUMMARY_TRIGGER_MESSAGES
CONVERSATION_SUMMARY_KEEP_RECENT_MESSAGES = settings.CONVERSATION_SUMMARY_KEEP_RECENT_MESSAGES
CONVERSATION_SUMMARY_REFRESH_MIN_MESSAGES = settings.CONVERSATION_SUMMARY_REFRESH_MIN_MESSAGES
CONVERSATION_SUMMARY_MAX_TOKENS = settings.CONVERSATION_SUMMARY_MAX_TOKENS


def estimate_tokens(text: str) -> int:
    return max(1, len(text) // 4)
