import logging
import os
import uuid
import hashlib
from typing import Optional

from docx import Document
from docx.shared import Inches, Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH

from app.config import settings

logger = logging.getLogger(__name__)


async def create_approval_note(
    artifact_id: str,
    content: str,
    title: str = "Approval Note",
    author: str = "Sovereign AI",
) -> str:
    """
    Create a Word document approval note.

    Args:
        artifact_id: Unique identifier for the artifact
        content: Main content of the document
        title: Document title
        author: Document author

    Returns:
        Path to the created document
    """
    try:
        doc = Document()

        title_para = doc.add_heading(title, 0)
        title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

        doc.add_paragraph(f"Generated by: {author}")
        doc.add_paragraph(f"Date: {__import__('datetime').datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        doc.add_paragraph(f"Document ID: {artifact_id}")

        doc.add_paragraph()

        for para in content.split("\n\n"):
            if para.strip():
                doc.add_paragraph(para.strip())

        os.makedirs(settings.ARTIFACT_DIR, exist_ok=True)
        filename = f"{artifact_id}.docx"
        filepath = os.path.join(settings.ARTIFACT_DIR, filename)

        doc.save(filepath)

        logger.info(f"Created approval note: {filepath}")
        return filepath

    except Exception as e:
        logger.error(f"DOCX creation error: {e}")
        raise


async def create_document(
    artifact_id: str,
    title: str,
    sections: list,
    author: str = "Sovereign AI",
) -> str:
    """
    Create a general Word document with sections.

    Args:
        artifact_id: Unique identifier
        title: Document title
        sections: List of dicts with 'heading' and 'content' keys
        author: Document author

    Returns:
        Path to the created document
    """
    try:
        doc = Document()

        title_para = doc.add_heading(title, 0)
        title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

        doc.add_paragraph(f"Author: {author}")
        doc.add_paragraph(f"Generated: {__import__('datetime').datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")

        doc.add_page_break()

        for section in sections:
            doc.add_heading(section.get("heading", ""), level=1)
            doc.add_paragraph(section.get("content", ""))

        os.makedirs(settings.ARTIFACT_DIR, exist_ok=True)
        filename = f"{artifact_id}.docx"
        filepath = os.path.join(settings.ARTIFACT_DIR, filename)

        doc.save(filepath)
        return filepath

    except Exception as e:
        logger.error(f"DOCX creation error: {e}")
        raise
