import logging
import os
from typing import List, Dict, Any
from datetime import datetime

from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN
from pptx.dml.color import RGBColor

from app.config import settings

logger = logging.getLogger(__name__)


async def create_presentation(
    artifact_id: str,
    title: str,
    slides: List[Dict[str, str]],
) -> str:
    """
    Create a PowerPoint presentation.

    Args:
        artifact_id: Unique identifier
        title: Presentation title
        slides: List of dicts with 'title' and 'content' keys

    Returns:
        Path to the created presentation
    """
    try:
        prs = Presentation()
        prs.slide_width = Inches(13.333)
        prs.slide_height = Inches(7.5)

        title_slide_layout = prs.slide_layouts[0]
        title_slide = prs.slides.add_slide(title_slide_layout)
        title_slide.shapes.title.text = title
        title_slide.placeholders[1].text = f"Generated by Sovereign AI\n{datetime.now().strftime('%Y-%m-%d')}"

        for slide_data in slides:
            content_slide_layout = prs.slide_layouts[1]
            slide = prs.slides.add_slide(content_slide_layout)

            if "title" in slide_data:
                slide.shapes.title.text = slide_data["title"]

            if "content" in slide_data:
                slide.placeholders[1].text = slide_data["content"]

        os.makedirs(settings.ARTIFACT_DIR, exist_ok=True)
        filename = f"{artifact_id}.pptx"
        filepath = os.path.join(settings.ARTIFACT_DIR, filename)

        prs.save(filepath)
        logger.info(f"Created presentation: {filepath}")
        return filepath

    except Exception as e:
        logger.error(f"PPTX creation error: {e}")
        raise
