# Standardized Security Events
EVENT_SECURITY_STARTUP = "SECURITY_STARTUP"
EVENT_CONFIG_CHANGED = "CONFIG_CHANGED"

EVENT_INPUT_ACCEPTED = "INPUT_ACCEPTED"
EVENT_INPUT_DENIED = "INPUT_DENIED"

EVENT_PROMPT_INJECTION_DETECTED = "PROMPT_INJECTION_DETECTED"
EVENT_PROMPT_ACCEPTED = "PROMPT_ACCEPTED"

EVENT_OUTPUT_ACCEPTED = "OUTPUT_ACCEPTED"
EVENT_OUTPUT_DENIED = "OUTPUT_DENIED"

EVENT_TOOL_AUTHORIZED = "TOOL_AUTHORIZED"
EVENT_TOOL_DENIED = "TOOL_DENIED"

EVENT_RAG_CONTENT_ACCEPTED = "RAG_CONTENT_ACCEPTED"
EVENT_RAG_CONTENT_DENIED = "RAG_CONTENT_DENIED"

EVENT_NETWORK_ENDPOINT_ACCEPTED = "NETWORK_ENDPOINT_ACCEPTED"
EVENT_NETWORK_ENDPOINT_DENIED = "NETWORK_ENDPOINT_DENIED"

EVENT_SECRET_DETECTED = "SECRET_DETECTED"

EVENT_POLICY_VIOLATION = "POLICY_VIOLATION"
